### ISSUE TITLE
Add loot for defeating enemies

### ISSUE THREAD

**Issue by TerrenceJChan** [TerrenceJChan/discord-rpg-game#7]
When enemies and monsters die, they should drop loot based on a percentage chance.

### To-Do
- Add loot to enemy object
- Loot should have a description of what they are
- Loot drop chance should be based on a percentage
- Should be added to a player's inventory in their object once an enemy is defeated

**Comment by foxfriends** [comment]
ohh i see you assigned yourself this one ok i will do another one
